# Generated by Django 3.2.6 on 2021-08-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210805_2330'),
        ('users', '0002_auto_20210806_1243'),
    ]

    operations = [
    ]
