# Generated by Django 3.2.6 on 2021-08-05 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeassetrequest',
            old_name='request_detail',
            new_name='request_details',
        ),
    ]
