# Generated by Django 3.2.6 on 2021-08-06 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeassetrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_asset_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeassetrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='managerrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='managerrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=50),
        ),
    ]
