# Generated by Django 3.2.6 on 2021-08-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20210804_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeassetrequest',
            name='type',
            field=models.CharField(choices=[('new_asset', 'new_asset'), ('repair', 'repair'), ('replacement', 'replacement')], default='new_asset', max_length=50),
        ),
    ]
