# Generated by Django 3.2.5 on 2021-08-06 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0002_auto_20210806_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managerrequest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='managerrequest',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
