# Generated by Django 3.2.5 on 2021-08-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_managerrequest_status'),
        ('assets', '0004_alter_profile_department'),
    ]

    operations = [
    ]
